export const liveScores = [
    {
        id: 1,
        team: "KC",
        mints: 10,
        wcw: 3669,
        divisional: 4000,
        conference: null,
        finals: null,
        ev: 0.02000,
    },
    {
        id: 2,
        team: "BUF",
        mints: 9,
        wcw: 3669,
        divisional: null,
        conference: null,
        finals: null,
        ev: 0.02038,
    },
    {
        id: 3,
        team: "SF",
        mints: 9,
        wcw: 3669,
        divisional: 4000,
        conference: null,
        finals: null,
        ev: 0.04260,
    },
    {
        id: 4,
        team: "PHIL",
        mints: 7,
        wcw: 3669,
        divisional: 4000,
        conference: null,
        finals: null,
        ev: 0.02857,
    },
    {
        id: 5,
        team: "CIN",
        mints: 5,
        wcw: 3669,
        divisional: 4000,
        conference: null,
        finals: null,
        ev: 0.07668,
    },
    {
        id: 6,
        team: "MIN",
        mints: 5,
        wcw: null,
        divisional: null,
        conference: null,
        finals: null,
        ev: null,
    },
    {
        id: 7,
        team: "JAX",
        mints: 4,
        wcw: 3669,
        divisional: null,
        conference: null,
        finals: null,
        ev: 0.04585,
    },
    {
        id: 8,
        team: "TAMPA",
        mints: 4,
        wcw: null,
        divisional: null,
        conference: null,
        finals: null,
        ev: null,
    },
    {
        id: 9,
        team: "LA",
        mints: 5,
        wcw: null,
        divisional: null,
        conference: null,
        finals: null,
        ev: null,
    },
    {
        id: 10,
        team: "DAL",
        mints: 3,
        wcw: 3669,
        divisional: null,
        conference: null,
        finals: null,
        ev: 0.06114,
    },
    {
        id: 11,
        team: "BAL",
        mints: 3,
        wcw: null,
        divisional: null,
        conference: null,
        finals: null,
        ev: null,
    },
    {
        id: 12,
        team: "NYG",
        mints: 3,
        wcw: 3669,
        divisional: null,
        conference: null,
        finals: null,
        ev: 0.06114,
    },
    {
        id: 13,
        team: "SEA",
        mints: 4,
        wcw: null,
        divisional: null,
        conference: null,
        finals: null,
        ev: null,
    },
    {
        id: 14,
        team: "MIA",
        mints: 3,
        wcw: null,
        divisional: null,
        conference: null,
        finals: null,
        ev: null,
    },
]
